resolver: nightly-2019-03-05
packages:
  - '.'
extra-deps:
  - git: https://github.com/tonatona-project/tonatona
    commit: 90fa2abcfcc7077c2bb3bdf04a85752aab19725e
    subdirs:
      - tonalude
      - tonaparser
      - tonatona
      - tonatona-logger
      - tonatona-persistent-postgresql
      - tonatona-persistent-sqlite
      - tonatona-servant
  - git: https://github.com/mojamozya/haskell-google-server-api
    commit: 029bfe2ea701a782209924731f51c8f84aef3371

flags: {}
extra-package-dbs: []
